In [1]:
import pandas as pd

# The final, clean load of your February data
# We use forward slashes (/) to keep Python happy on Windows
df = pd.read_csv('../data/fii_history_2026-02.csv')

# Look at the first 5 rows to make sure the columns are correct
print("✅ Project Database: Connected")
df.head()

✅ Project Database: Connected

,FII Rs Crores,Unnamed: 1,Unnamed: 2,DII Rs Crores,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Date,Gross Purchase,Gross Sales,Net Purchase / Sales,Gross Purchase,Gross Sales,Net Purchase / Sales
1,Total,339315.95,345956.73,-6640.78,346722.22,308299.11,38423.11
2,27-Feb-2026,"36,699.66","44,236.02","-7,536.36","24,867.72","12,574.91","12,292.81"
3,26-Feb-2026,"14,607.90","18,073.89","-3,465.99","19,242.72","14,211.15","5,031.57"
4,25-Feb-2026,"30,369.48","27,377.84","2,991.64","18,346.49","13,227.92","5,118.57"

In [2]:
# 1. Skip the first two rows and rename columns for clarity
df_clean = df.iloc[2:].copy()
df_clean.columns = ['Date', 'FII_Buy', 'FII_Sell', 'FII_Net', 'DII_Buy', 'DII_Sell', 'DII_Net']

# 2. Reset the index so it starts from 0 again
df_clean = df_clean.reset_index(drop=True)

# 3. Convert numbers to actual floats (decimals) so we can do math
# We have to remove the commas first!
cols_to_fix = ['FII_Buy', 'FII_Sell', 'FII_Net', 'DII_Buy', 'DII_Sell', 'DII_Net']
for col in cols_to_fix:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

print("✅ Stage 2: Data Cleaning Complete")
df_clean.head()

✅ Stage 2: Data Cleaning Complete

          Date  FII_Buy  FII_Sell  FII_Net  DII_Buy  DII_Sell  DII_Net
0  27-Feb-2026      NaN       NaN      NaN      NaN       NaN      NaN
1  26-Feb-2026      NaN       NaN      NaN      NaN       NaN      NaN
2  25-Feb-2026      NaN       NaN      NaN      NaN       NaN      NaN
3  24-Feb-2026      NaN       NaN  -102.53      NaN       NaN      NaN
4  23-Feb-2026      NaN       NaN      NaN      NaN       NaN      NaN

In [3]:
# 1. Skip the junk headers and rename
df_clean = df.iloc[2:].copy()
df_clean.columns = ['Date', 'FII_Buy', 'FII_Sell', 'FII_Net', 'DII_Buy', 'DII_Sell', 'DII_Net']

# 2. Reset the index
df_clean = df_clean.reset_index(drop=True)

# 3. THE FIX: Remove commas and whitespace before converting to numbers
cols_to_fix = ['FII_Buy', 'FII_Sell', 'FII_Net', 'DII_Buy', 'DII_Sell', 'DII_Net']

for col in cols_to_fix:
    # This line removes commas and extra spaces
    df_clean[col] = df_clean[col].astype(str).str.replace(',', '').str.strip()
    # Now we convert to actual numbers
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

print("✅ Stage 2: Data Cleaning Complete (Commas Removed)")
df_clean.head()

✅ Stage 2: Data Cleaning Complete (Commas Removed)

          Date   FII_Buy  FII_Sell  FII_Net   DII_Buy  DII_Sell   DII_Net
0  27-Feb-2026  36699.66  44236.02 -7536.36  24867.72  12574.91  12292.81
1  26-Feb-2026  14607.90  18073.89 -3465.99  19242.72  14211.15   5031.57
2  25-Feb-2026  30369.48  27377.84  2991.64  18346.49  13227.92   5118.57
3  24-Feb-2026  20550.91  20653.44  -102.53  18580.96  15419.74   3161.22
4  23-Feb-2026  15294.02  11810.32  3483.70  12360.86  13653.10  -1292.24

In [4]:
# Calculate Total Net Flows
fii_net_total = df_clean['FII_Net'].sum()
dii_net_total = df_clean['DII_Net'].sum()

print(f"📊 FEBRUARY 2026 MARKET SUMMARY")
print(f"-------------------------------")
print(f"FII Net Movement: {fii_net_total:,.2f} Cr")
print(f"DII Net Movement: {dii_net_total:,.2f} Cr")

# Logic to determine who is driving the market
if fii_net_total < 0 and dii_net_total > 0:
    print("\n⚠️ TREND: FIIs are exiting, but DIIs are absorbing the pressure.")
elif fii_net_total > 0:
    print("\n🚀 TREND: FIIs are bullish. Global money is flowing in!")

📊 FEBRUARY 2026 MARKET SUMMARY
-------------------------------
FII Net Movement: -6,640.78 Cr
DII Net Movement: 38,423.11 Cr

⚠️ TREND: FIIs are exiting, but DIIs are absorbing the pressure.

In [5]:
# 1. Find the 3 biggest selling days by FIIs
top_selling = df_clean.sort_values(by='FII_Net', ascending=True).head(3)

# 2. Find the 3 biggest buying days by FIIs
top_buying = df_clean.sort_values(by='FII_Net', ascending=False).head(3)

print("🚨 TOP 3 PANIC DAYS (Highest FII Selling):")
print(top_selling[['Date', 'FII_Net']])

print("\n💎 TOP 3 ACCUMULATION DAYS (Highest FII Buying):")
print(top_buying[['Date', 'FII_Net']])

🚨 TOP 3 PANIC DAYS (Highest FII Selling):
           Date  FII_Net
0   27-Feb-2026 -7536.36
10  13-Feb-2026 -7395.41
1   26-Feb-2026 -3465.99

💎 TOP 3 ACCUMULATION DAYS (Highest FII Buying):
           Date  FII_Net
18  03-Feb-2026  5236.28
4   23-Feb-2026  3483.70
2   25-Feb-2026  2991.64

In [6]:
# Save the cleaned Feb data as the foundation of your Master DB
df_clean.to_csv('../data/fii_dii_master_database.csv', index=False)

print("🗄️ Master Database Initialized: C:/dev/nse-market-intelligence-suite/data/fii_dii_master_database.csv")

🗄️ Master Database Initialized: C:/dev/nse-market-intelligence-suite/data/fii_dii_master_database.csv

In [7]:
import pandas as pd

def clean_data(file_path):
    # Load and skip headers
    raw = pd.read_csv(file_path)
    clean = raw.iloc[2:].copy()
    clean.columns = ['Date', 'FII_Buy', 'FII_Sell', 'FII_Net', 'DII_Buy', 'DII_Sell', 'DII_Net']
    
    # Remove commas and convert to numbers
    cols = ['FII_Buy', 'FII_Sell', 'FII_Net', 'DII_Buy', 'DII_Sell', 'DII_Net']
    for col in cols:
        clean[col] = clean[col].astype(str).str.replace(',', '').str.strip()
        clean[col] = pd.to_numeric(clean[col], errors='coerce')
    
    return clean.dropna(subset=['Date'])

# 1. Load the new raw months
jan = clean_data('../data/fii_raw_jan_2026.csv')
march = clean_data('../data/fii_raw_march_2026.csv')

# 2. Load your current Master DB (which has Feb)
master_df = pd.read_csv('../data/fii_dii_master_database.csv')

# 3. Combine them all
final_db = pd.concat([master_df, jan, march], ignore_index=True)

# 4. Remove duplicates (In case you run this twice)
final_db = final_db.drop_duplicates(subset=['Date'])

# 5. Save it back to the Master
final_db.to_csv('../data/fii_dii_master_database.csv', index=False)

print(f"✅ Mission Accomplished. Master DB now has {len(final_db)} days of market history.")
final_db.head()

✅ Mission Accomplished. Master DB now has 49 days of market history.

          Date   FII_Buy  FII_Sell  FII_Net   DII_Buy  DII_Sell   DII_Net
0  27-Feb-2026  36699.66  44236.02 -7536.36  24867.72  12574.91  12292.81
1  26-Feb-2026  14607.90  18073.89 -3465.99  19242.72  14211.15   5031.57
2  25-Feb-2026  30369.48  27377.84  2991.64  18346.49  13227.92   5118.57
3  24-Feb-2026  20550.91  20653.44  -102.53  18580.96  15419.74   3161.22
4  23-Feb-2026  15294.02  11810.32  3483.70  12360.86  13653.10  -1292.24

In [8]:
final_db

           Date   FII_Buy  FII_Sell  FII_Net   DII_Buy  DII_Sell   DII_Net
0   27-Feb-2026  36699.66  44236.02 -7536.36  24867.72  12574.91  12292.81
1   26-Feb-2026  14607.90  18073.89 -3465.99  19242.72  14211.15   5031.57
2   25-Feb-2026  30369.48  27377.84  2991.64  18346.49  13227.92   5118.57
3   24-Feb-2026  20550.91  20653.44  -102.53  18580.96  15419.74   3161.22
4   23-Feb-2026  15294.02  11810.32  3483.70  12360.86  13653.10  -1292.24
5   20-Feb-2026  10010.06  10944.67  -934.61  14901.90  12264.75   2637.15
6   19-Feb-2026   8614.90   9495.39  -880.49  11483.86  12080.14   -596.28
7   18-Feb-2026   9720.92   8566.58  1154.34  12143.76  11703.42    440.34
8   17-Feb-2026   8867.62   7872.41   995.21  12482.64  12295.60    187.04
9   16-Feb-2026   9169.39  10141.52  -972.13  13121.31  11454.33   1666.98
10  13-Feb-2026  14586.73  21982.14 -7395.41  20605.87  15051.91   5553.96
11  12-Feb-2026  17949.52  17841.10   108.42  17213.85  16937.00    276.85
12  11-Feb-2026  16858.63  15914.82   943.81  14281.26  14406.62   -125.36
13  10-Feb-2026  16699.82  16630.37    69.45  15262.90  14088.69   1174.21
14  09-Feb-2026  16066.13  13811.49  2254.64  13572.99  13568.84      4.15
15  06-Feb-2026  16718.66  14767.89  1950.77  13215.74  14480.80  -1265.06
16  05-Feb-2026  14630.07  16780.58 -2150.51  15182.18  14052.36   1129.82
17  04-Feb-2026  18453.01  18423.22    29.79  18631.78  18382.24    249.54
18  03-Feb-2026  27677.68  22441.40  5236.28  28206.21  27191.97   1014.24
19  02-Feb-2026  15172.55  17005.01 -1832.46  18626.43  16180.10   2446.33
20  01-Feb-2026    598.29   1186.63  -588.34  14390.79  15073.52   -682.73
21  30-Jan-2026  30492.98  28241.61  2251.37  18590.13  19191.16   -601.03
22  29-Jan-2026  20212.73  20606.70  -393.97  24423.89  21785.13   2638.76
23  28-Jan-2026  21044.50  20564.24   480.26  19578.39  16217.80   3360.59
24  27-Jan-2026  29666.67  32735.16 -3068.49  23929.34  14929.63   8999.71
25  23-Jan-2026  13550.25  17663.63 -4113.38  18258.75  14156.19   4102.56
26  22-Jan-2026  16873.20  19423.00 -2549.80  17537.49  13314.51   4222.98
27  21-Jan-2026  15370.98  17158.64 -1787.66  17387.34  12866.87   4520.47
28  20-Jan-2026  14215.11  17153.44 -2938.33  18529.36  14863.67   3665.69
29  19-Jan-2026  12379.75  15642.57 -3262.82  17887.61  13653.31   4234.30
30  16-Jan-2026  20159.84  24505.97 -4346.13  19135.42  15200.11   3935.31
31  14-Jan-2026  13121.23  17902.47 -4781.24  19930.32  14713.04   5217.28
32  13-Jan-2026  11994.92  13494.73 -1499.81  15445.22  14263.44   1181.78
33  12-Jan-2026   9071.61  12710.01 -3638.40  16985.90  11146.58   5839.32
34  09-Jan-2026  11093.29  14862.60 -3769.31  18481.07  12885.23   5595.84
35  08-Jan-2026  11090.27  14457.39 -3367.12  18707.23  15006.06   3701.17
36  07-Jan-2026  14663.53  16191.24 -1527.71  18364.76  15475.44   2889.32
37  06-Jan-2026  15061.18  15168.81  -107.63  17240.41  15491.06   1749.35
38  05-Jan-2026  11277.44  11313.69   -36.25  15565.79  13801.72   1764.07
39  02-Jan-2026   7850.45   7560.65   289.80  15349.56  14672.18    677.38
40  01-Jan-2026   1067.64   4336.24 -3268.60  13045.31  11519.42   1525.89
41  12-Mar-2026  15373.05  22422.92 -7049.87  19439.56  11989.79   7449.77
42  11-Mar-2026  11448.68  17715.99 -6267.31  16044.16  11078.63   4965.53
43  10-Mar-2026  13188.32  17860.96 -4672.64  17202.49  10869.23   6333.26
44  09-Mar-2026  11156.99  17502.56 -6345.57  21586.46  12572.66   9013.80
45  06-Mar-2026  14434.69  20465.07 -6030.38  19662.38  12690.87   6971.51
46  05-Mar-2026  14914.99  18667.51 -3752.52  18821.10  13667.73   5153.37
47  04-Mar-2026  19120.99  27873.64 -8752.65  26259.37  14191.20  12068.17
48  02-Mar-2026  12737.34  16032.98 -3295.64  21110.66  12516.79   8593.87

In [10]:
master_df

           Date   FII_Buy  FII_Sell  FII_Net   DII_Buy  DII_Sell   DII_Net
0   27-Feb-2026  36699.66  44236.02 -7536.36  24867.72  12574.91  12292.81
1   26-Feb-2026  14607.90  18073.89 -3465.99  19242.72  14211.15   5031.57
2   25-Feb-2026  30369.48  27377.84  2991.64  18346.49  13227.92   5118.57
3   24-Feb-2026  20550.91  20653.44  -102.53  18580.96  15419.74   3161.22
4   23-Feb-2026  15294.02  11810.32  3483.70  12360.86  13653.10  -1292.24
5   20-Feb-2026  10010.06  10944.67  -934.61  14901.90  12264.75   2637.15
6   19-Feb-2026   8614.90   9495.39  -880.49  11483.86  12080.14   -596.28
7   18-Feb-2026   9720.92   8566.58  1154.34  12143.76  11703.42    440.34
8   17-Feb-2026   8867.62   7872.41   995.21  12482.64  12295.60    187.04
9   16-Feb-2026   9169.39  10141.52  -972.13  13121.31  11454.33   1666.98
10  13-Feb-2026  14586.73  21982.14 -7395.41  20605.87  15051.91   5553.96
11  12-Feb-2026  17949.52  17841.10   108.42  17213.85  16937.00    276.85
12  11-Feb-2026  16858.63  15914.82   943.81  14281.26  14406.62   -125.36
13  10-Feb-2026  16699.82  16630.37    69.45  15262.90  14088.69   1174.21
14  09-Feb-2026  16066.13  13811.49  2254.64  13572.99  13568.84      4.15
15  06-Feb-2026  16718.66  14767.89  1950.77  13215.74  14480.80  -1265.06
16  05-Feb-2026  14630.07  16780.58 -2150.51  15182.18  14052.36   1129.82
17  04-Feb-2026  18453.01  18423.22    29.79  18631.78  18382.24    249.54
18  03-Feb-2026  27677.68  22441.40  5236.28  28206.21  27191.97   1014.24
19  02-Feb-2026  15172.55  17005.01 -1832.46  18626.43  16180.10   2446.33
20  01-Feb-2026    598.29   1186.63  -588.34  14390.79  15073.52   -682.73

In [11]:
# Check the total count
print(f"Total trading days in database: {len(master_df)}")

# Sort by date so March appears at the top
master_df['Date'] = pd.to_datetime(master_df['Date']) # Ensure Python knows these are dates
master_df = master_df.sort_values(by='Date', ascending=False)

# Now check the top 10 rows
master_df.head(10)

Total trading days in database: 21

        Date   FII_Buy  FII_Sell  FII_Net   DII_Buy  DII_Sell   DII_Net
0 2026-02-27  36699.66  44236.02 -7536.36  24867.72  12574.91  12292.81
1 2026-02-26  14607.90  18073.89 -3465.99  19242.72  14211.15   5031.57
2 2026-02-25  30369.48  27377.84  2991.64  18346.49  13227.92   5118.57
3 2026-02-24  20550.91  20653.44  -102.53  18580.96  15419.74   3161.22
4 2026-02-23  15294.02  11810.32  3483.70  12360.86  13653.10  -1292.24
5 2026-02-20  10010.06  10944.67  -934.61  14901.90  12264.75   2637.15
6 2026-02-19   8614.90   9495.39  -880.49  11483.86  12080.14   -596.28
7 2026-02-18   9720.92   8566.58  1154.34  12143.76  11703.42    440.34
8 2026-02-17   8867.62   7872.41   995.21  12482.64  12295.60    187.04
9 2026-02-16   9169.39  10141.52  -972.13  13121.31  11454.33   1666.98

In [12]:
import pandas as pd

# 1. The Pro-Cleaning Function
def clean_month(file_path):
    raw = pd.read_csv(file_path)
    # Skip the junk headers from the website copy-paste
    clean = raw.iloc[2:].copy()
    clean.columns = ['Date', 'FII_Buy', 'FII_Sell', 'FII_Net', 'DII_Buy', 'DII_Sell', 'DII_Net']
    
    # Scrub commas and fix numbers
    cols = ['FII_Buy', 'FII_Sell', 'FII_Net', 'DII_Buy', 'DII_Sell', 'DII_Net']
    for col in cols:
        clean[col] = clean[col].astype(str).str.replace(',', '').str.strip()
        clean[col] = pd.to_numeric(clean[col], errors='coerce')
    
    return clean.dropna(subset=['Date'])

# 2. Build the database by stacking the months
print("🏗️ Building Master Database...")

# Process each raw file
jan = clean_month('../data/fii_raw_jan_2026.csv')
feb = clean_month('../data/fii_history_2026-02.csv') # Use your Feb raw file here
mar = clean_month('../data/fii_raw_march_2026.csv')

# Stack them vertically
master_df = pd.concat([mar, feb, jan], ignore_index=True)

# 3. Final Polish
master_df = master_df.drop_duplicates(subset=['Date'])
master_df.to_csv('../data/fii_dii_master_database.csv', index=False)

print(f"✅ SUCCESS! Your database now has {len(master_df)} trading days.")
print("Dates covered:", master_df['Date'].min(), "to", master_df['Date'].max())
master_df.head(10)

🏗️ Building Master Database...
✅ SUCCESS! Your database now has 49 trading days.
Dates covered: 01-Feb-2026 to 30-Jan-2026

          Date   FII_Buy  FII_Sell  FII_Net   DII_Buy  DII_Sell   DII_Net
0  12-Mar-2026  15373.05  22422.92 -7049.87  19439.56  11989.79   7449.77
1  11-Mar-2026  11448.68  17715.99 -6267.31  16044.16  11078.63   4965.53
2  10-Mar-2026  13188.32  17860.96 -4672.64  17202.49  10869.23   6333.26
3  09-Mar-2026  11156.99  17502.56 -6345.57  21586.46  12572.66   9013.80
4  06-Mar-2026  14434.69  20465.07 -6030.38  19662.38  12690.87   6971.51
5  05-Mar-2026  14914.99  18667.51 -3752.52  18821.10  13667.73   5153.37
6  04-Mar-2026  19120.99  27873.64 -8752.65  26259.37  14191.20  12068.17
7  02-Mar-2026  12737.34  16032.98 -3295.64  21110.66  12516.79   8593.87
8  27-Feb-2026  36699.66  44236.02 -7536.36  24867.72  12574.91  12292.81
9  26-Feb-2026  14607.90  18073.89 -3465.99  19242.72  14211.15   5031.57

In [13]:
master_df

           Date   FII_Buy  FII_Sell  FII_Net   DII_Buy  DII_Sell   DII_Net
0   12-Mar-2026  15373.05  22422.92 -7049.87  19439.56  11989.79   7449.77
1   11-Mar-2026  11448.68  17715.99 -6267.31  16044.16  11078.63   4965.53
2   10-Mar-2026  13188.32  17860.96 -4672.64  17202.49  10869.23   6333.26
3   09-Mar-2026  11156.99  17502.56 -6345.57  21586.46  12572.66   9013.80
4   06-Mar-2026  14434.69  20465.07 -6030.38  19662.38  12690.87   6971.51
5   05-Mar-2026  14914.99  18667.51 -3752.52  18821.10  13667.73   5153.37
6   04-Mar-2026  19120.99  27873.64 -8752.65  26259.37  14191.20  12068.17
7   02-Mar-2026  12737.34  16032.98 -3295.64  21110.66  12516.79   8593.87
8   27-Feb-2026  36699.66  44236.02 -7536.36  24867.72  12574.91  12292.81
9   26-Feb-2026  14607.90  18073.89 -3465.99  19242.72  14211.15   5031.57
10  25-Feb-2026  30369.48  27377.84  2991.64  18346.49  13227.92   5118.57
11  24-Feb-2026  20550.91  20653.44  -102.53  18580.96  15419.74   3161.22
12  23-Feb-2026  15294.02  11810.32  3483.70  12360.86  13653.10  -1292.24
13  20-Feb-2026  10010.06  10944.67  -934.61  14901.90  12264.75   2637.15
14  19-Feb-2026   8614.90   9495.39  -880.49  11483.86  12080.14   -596.28
15  18-Feb-2026   9720.92   8566.58  1154.34  12143.76  11703.42    440.34
16  17-Feb-2026   8867.62   7872.41   995.21  12482.64  12295.60    187.04
17  16-Feb-2026   9169.39  10141.52  -972.13  13121.31  11454.33   1666.98
18  13-Feb-2026  14586.73  21982.14 -7395.41  20605.87  15051.91   5553.96
19  12-Feb-2026  17949.52  17841.10   108.42  17213.85  16937.00    276.85
20  11-Feb-2026  16858.63  15914.82   943.81  14281.26  14406.62   -125.36
21  10-Feb-2026  16699.82  16630.37    69.45  15262.90  14088.69   1174.21
22  09-Feb-2026  16066.13  13811.49  2254.64  13572.99  13568.84      4.15
23  06-Feb-2026  16718.66  14767.89  1950.77  13215.74  14480.80  -1265.06
24  05-Feb-2026  14630.07  16780.58 -2150.51  15182.18  14052.36   1129.82
25  04-Feb-2026  18453.01  18423.22    29.79  18631.78  18382.24    249.54
26  03-Feb-2026  27677.68  22441.40  5236.28  28206.21  27191.97   1014.24
27  02-Feb-2026  15172.55  17005.01 -1832.46  18626.43  16180.10   2446.33
28  01-Feb-2026    598.29   1186.63  -588.34  14390.79  15073.52   -682.73
29  30-Jan-2026  30492.98  28241.61  2251.37  18590.13  19191.16   -601.03
30  29-Jan-2026  20212.73  20606.70  -393.97  24423.89  21785.13   2638.76
31  28-Jan-2026  21044.50  20564.24   480.26  19578.39  16217.80   3360.59
32  27-Jan-2026  29666.67  32735.16 -3068.49  23929.34  14929.63   8999.71
33  23-Jan-2026  13550.25  17663.63 -4113.38  18258.75  14156.19   4102.56
34  22-Jan-2026  16873.20  19423.00 -2549.80  17537.49  13314.51   4222.98
35  21-Jan-2026  15370.98  17158.64 -1787.66  17387.34  12866.87   4520.47
36  20-Jan-2026  14215.11  17153.44 -2938.33  18529.36  14863.67   3665.69
37  19-Jan-2026  12379.75  15642.57 -3262.82  17887.61  13653.31   4234.30
38  16-Jan-2026  20159.84  24505.97 -4346.13  19135.42  15200.11   3935.31
39  14-Jan-2026  13121.23  17902.47 -4781.24  19930.32  14713.04   5217.28
40  13-Jan-2026  11994.92  13494.73 -1499.81  15445.22  14263.44   1181.78
41  12-Jan-2026   9071.61  12710.01 -3638.40  16985.90  11146.58   5839.32
42  09-Jan-2026  11093.29  14862.60 -3769.31  18481.07  12885.23   5595.84
43  08-Jan-2026  11090.27  14457.39 -3367.12  18707.23  15006.06   3701.17
44  07-Jan-2026  14663.53  16191.24 -1527.71  18364.76  15475.44   2889.32
45  06-Jan-2026  15061.18  15168.81  -107.63  17240.41  15491.06   1749.35
46  05-Jan-2026  11277.44  11313.69   -36.25  15565.79  13801.72   1764.07
47  02-Jan-2026   7850.45   7560.65   289.80  15349.56  14672.18    677.38
48  01-Jan-2026   1067.64   4336.24 -3268.60  13045.31  11519.42   1525.89